# Generated by Django 5.2.14 on 2026-06-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_enterprise_product_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL of the product's main image"),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('insecticide', 'Insecticide'), ('fungicide', 'Fungicide'), ('herbicide', 'Herbicide'), ('miticide', 'Miticides'), ('public_health', 'Public Health'), ('pgr', 'Plant Growth Regulator'), ('aquaculture', 'Aquaculture'), ('rodenticide', 'Rodenticide'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
