# Generated by Django 5.2.14 on 2026-06-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_url_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='formulation',
            field=models.CharField(blank=True, help_text='Active ingredient / strength', max_length=500),
        ),
    ]
